# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-27 07:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_sno', models.IntegerField()),
                ('ques_text', models.TextField()),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('correct', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_enrollmentno', models.IntegerField()),
                ('student_phoneno', models.IntegerField()),
                ('student_father_name', models.CharField(max_length=100)),
                ('student_mother_name', models.CharField(max_length=100)),
                ('student_address', models.CharField(max_length=200)),
                ('student_pic', models.ImageField(upload_to='pic_folder/')),
                ('student_city', models.CharField(max_length=30)),
                ('student_state', models.CharField(max_length=30)),
                ('student_pincode', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_sno', models.IntegerField()),
                ('teacher_salary', models.IntegerField()),
                ('teacher_qualification', models.CharField(max_length=100)),
                ('teacher_phoneno', models.IntegerField()),
                ('teacher_address', models.CharField(max_length=200)),
                ('teacher_pic', models.ImageField(upload_to='pic_folder/')),
                ('teacher_city', models.CharField(max_length=30)),
                ('teacher_state', models.CharField(max_length=30)),
                ('teacher_pincode', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
