# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-05 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqtest', '0010_auto_20180705_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_name',
            field=models.CharField(max_length=30),
        ),
    ]
