# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-05 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqtest', '0011_auto_20180705_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ques_sno',
            field=models.CharField(max_length=10),
        ),
    ]
