# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-05 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcqtest', '0012_auto_20180705_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='givequiz',
            name='quizname',
            field=models.ManyToManyField(related_name='givequizs', to='mcqtest.Quiz'),
        ),
        migrations.AlterField(
            model_name='givequiz',
            name='student',
            field=models.ManyToManyField(related_name='givequizs', to='mcqtest.Student'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mcqtest.Quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizs', to='mcqtest.Teacher'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentanswers', to='mcqtest.Student'),
        ),
        migrations.AlterField(
            model_name='takenquiz',
            name='quizgiven',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takenquizs', to='mcqtest.GiveQuiz'),
        ),
        migrations.AlterField(
            model_name='takenquiz',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takenquizs', to='mcqtest.Student'),
        ),
    ]
